# .project metadata for Operator Framework
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Add adopters list (ADOPTERS.md)
# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "operator-framework"
name: "Operator Framework"
description: "An open source toolkit to manage Kubernetes native applications, called Operators in an effective, automated, and scalable way. Provides managing controllers and developer tooling"
type: "project"
project_lead: "joelanford"
slack_channels:
  - name: "#olm-dev"
    workspace: "kubernetes"
    primary: true
  - name: "#operator-sdk-dev"
    workspace: "kubernetes"
  - name: "#olm-dev"
    workspace: "cncf"
  - name: "#operator-framework-community"
    workspace: "kubernetes"

maturity_log:
  - phase: "incubating"
    date: "2020-07-09T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/279"

repositories:
  - url: "https://github.com/operator-framework/operator-lifecycle-manager"
    primary: true
    tags: [on-cluster, olmv0]
  - url: "https://github.com/operator-framework/api"
    tags: [on-cluster, api, olmv0]
  - url: "https://github.com/operator-framework/operator-registry"
    tags: [on-cluster, registry, catalogs, fbc]
  - url: "https://github.com/operator-framework/olm-docs"
    tags: [documentation, docs]
  - url: "https://github.com/operator-framework/operator-sdk"
    tags: [developer, sdk]
  - url: "https://github.com/operator-framework/operator-controller"
    tags: [on-cluster, olmv1]
  - url: "https://github.com/operator-framework/java-operator-sdk"
    tags: [developer, sdk]
  - url: "https://github.com/operator-framework/josdk-spring-boot-starter"
    tags: [developer, sdk]
  - url: "https://github.com/operator-framework/josdk-webhooks"
    tags: [developer, sdk]
    # tags: [core, sig-apps] # Optional

website: "https://operatorframework.io/"

artwork: "https://landscape.cncf.io/logos/operator-framework.svg"

# TODO: Add ADOPTERS.md if your project tracks adopters
# adopters:
#   path: "https://github.com/operator-framework/operator-sdk/blob/master/ADOPTERS.md"


# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "operator-framework/operator-sdk"
#   TODO: once we nail down the canonical repos here we can add the images they use


#security:
#  policy:
#    path: "https://github.com/operator-framework/community/blob/master/SECURITY.md"
#  contact:
#    advisory_url: "https://github.com/operator-framework/operator-sdk/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/operator-framework/community/blob/master/contributor-ladder.md"
  code_of_conduct:
    path: "https://github.com/operator-framework/community/blob/master/code-of-conduct.md"

legal:
  license:
    path: "https://github.com/operator-framework/community/blob/master/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/operator-framework/community/blob/master/README.md"

landscape:
  category: "App Definition and Development"
  subcategory: "Application Definition & Image Build"

# CLOMonitor Score: 70/100
# Documentation: 82 | License: 86 | Best Practices: 46 | Security: 56
